results_path: ./results
fee_data_path: ./data/fee.npy
results_subdirs:
  - models_path: ./results/models
  - data_path: ./results/data
  - img_path: ./results/img
  - log_path: ./results/log
seed: 3407
max_agents_num: 100
lambd: .6
delta: 10
b: 20
is_burn: False
a: 1
