results_path: ./results
fee_data_path: ./data/fee.npy
results_subdirs:
  - ./results/models
  - ./results/data
  - ./results/img
  - ./results/log
seed: 3407
max_agents_num: 500               # number of txs in delta time, i.e. txs arrival rate in unit time * network propagation delay
lambd: 6                          # block generation (Poisson process or other) rate in unit time
delta: 1                          # network propagation delay (need div delta when calc throughput TPS)
b: 50                             # block size
is_burn: False                    # burn txs fee or not
a: 1                              # used in a * log(1 + x/a)
is_clip: True                     # clip private value to an upper bound
clip_value: 40000                 # upper bound value
