results_path: ./results
fee_data_path: ./data/fee.npy
results_subdirs:
  - ./results/models
  - ./results/data
  - ./results/img
  - ./results/log
seed: 3407
max_agents_num: 10 # 100
lambd: .6
delta: 10
b: 2 # 20
is_burn: True
a: 1 # * used in a * log(1 + x/a)
is_clip: True
clip_value: 40000
