path:
  model_path: ./results/models/cmaes.pth
  log_path: ./results/data/cmaes_log.csv
  sw_path: ./results/data/cmaes_sw.npy
model:
train:
  query_time: 500
  # expect_time: 10
  hidden_layer_size: (16,16)
eval:
  test_round: 1000
  query_time: 5000
  expect_time: 10
