steps: 3000
test_steps: 10
save_freq: 50
batch_size: 64
memory_size: 100000
gamma: 0.99
lr: .001
tau: 0.001
exp_std: 1
verify_std: 0.01
iterations: 1
epsilon_min: 0.1
epsilon_decay: 0.999
optim_idx: 0
optim_cnt: 100
