path:
  actor_model_path: ./results/models/ddpg_actor.pth
  critic_model_path: ./results/models/ddpg_critic.pth
  log_path: ./results/data/ddpg_log.csv
  rewards_path: ./results/data/ddpg_rewards.npy
  sw_path: ./results/data/ddpg_sw.npy
  epsilon_path: ./results/data/ddpg_epsilon.npy
model:
  gamma: 0.99 # not used
  actor_lr: .0001
  critic_lr: .001
  tau: 0.001
  batch_size: 64
  std: 50 # 50
  memory_size: 10000
  epsilon_min: 0.01
  epsilon_decay: 0.95
  iterations: 1
train:
  steps: 3000
  save_freq: 50
test:
  steps: 100
eval:
  steps: 20
  idx: 0
  cnt: 100
