path:
  model_path: ./results/models/es.pth
  log_path: ./results/data/es_log.csv
  sw_path: ./results/data/es_sw.npy
model:
train:
  iterations: 100
  oracle_query_times: 50
  alpha1: .01
  mu1: .1
  alpha2: .05
  mu2: .05
