train:
  outer_iterations: 10
  # inner_iterations: 20
  # inner_oracle_query_times: 80
  expect_time: 500
  # apr_test_times: 5
  # alpha1: .01
  # nu1: .1
  alpha2: .04
  nu2: .2
  eval_freq: 5
  is_load: False
eval:
  test_round: 100
test:
  test_round: 100
  max_lambd: 10
