path:
  model_path: ./results/models/nn.pth
  log_path: ./results/data/nn_log.csv
  rewards_path: ./results/data/nn_rewards.npy
  sw_path: ./results/data/nn_sw.npy
  loss_path: ./results/data/nn_loss.npy
  delta_rewards_path: ./results/data/nn_delta_rewards.npy
model:
train:
  epochs: 1000
  save_freq: 1
  cnt: 400
  lr: 0.0005
  batch_size: 4
eval:
  steps: 100
  cnt: 400
test:
  steps: 10000
